name: 'API tests'

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install node modules
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run test
        run: npm run test
